shortcut:
  auto_save: C, Space
  change_output_dir: Shift+Z
  clear: Ctrl+Shift+Z
  clear_label: ''
  clear_recent: ''
  close: Ctrl+W
  data_widget: ''
  del_active_polygon: Backspace
  del_all_polygon: ''
  edit_shortcuts: E
  export_label: ''
  finish_object: Space
  grid_ann_widget: ''
  import_label: ''
  label_widget: ''
  largest_component: ''
  load_param: Ctrl+M
  mi_widget: ''
  model_widget: ''
  open_folder: Shift+A
  open_image: Ctrl+A
  origional_extension: ''
  quick_start: ''
  quit: ''
  redo: Ctrl+Y
  report_bug: ''
  rs_widget: ''
  save: Ctrl+S
  save_as: ''
  save_coco: ''
  save_cutout: ''
  save_json: ''
  save_pseudo: ''
  segmentation_widget: ''
  set_cutout_background: ''
  turn_next: F
  turn_prev: S
  undo: Ctrl+Z
